UF_TO_REGION: dict[str, str] = {
    "AC": "Norte",
    "AP": "Norte",
    "AM": "Norte",
    "PA": "Norte",
    "RO": "Norte",
    "RR": "Norte",
    "TO": "Norte",
    "AL": "Nordeste",
    "BA": "Nordeste",
    "CE": "Nordeste",
    "MA": "Nordeste",
    "PB": "Nordeste",
    "PE": "Nordeste",
    "PI": "Nordeste",
    "RN": "Nordeste",
    "SE": "Nordeste",
    "DF": "Centro-Oeste",
    "GO": "Centro-Oeste",
    "MT": "Centro-Oeste",
    "MS": "Centro-Oeste",
    "ES": "Sudeste",
    "MG": "Sudeste",
    "RJ": "Sudeste",
    "SP": "Sudeste",
    "PR": "Sul",
    "RS": "Sul",
    "SC": "Sul",
}

CAUSE_MAPPING: dict[str, str] = {
    "Reação tardia ou ineficiente do condutor": "falha_atencao_reacao",
    "Ausência de reação do condutor": "falha_atencao_reacao",
    "Condutor deixou de manter distância do veículo da frente": (
        "falha_atencao_reacao"
    ),
    "Acessar a via sem observar a presença dos outros veículos": (
        "falha_atencao_reacao"
    ),
    "Manobra de mudança de faixa": "falha_atencao_reacao",
    "Condutor Dormindo": "falha_atencao_reacao",
    "Condutor usando celular": "falha_atencao_reacao",
    "Frear bruscamente": "falha_atencao_reacao",
    "Velocidade Incompatível": "infracao_comportamento_risco",
    "Ingestão de álcool pelo condutor": "infracao_comportamento_risco",
    "Ingestão de substâncias psicoativas pelo condutor": (
        "infracao_comportamento_risco"
    ),
    "Transitar na contramão": "infracao_comportamento_risco",
    "Ultrapassagem Indevida": "infracao_comportamento_risco",
    "Trafegar com motocicleta (ou similar) entre as faixas": (
        "infracao_comportamento_risco"
    ),
    "Desrespeitar a preferência no cruzamento": "infracao_comportamento_risco",
    "Conversão proibida": "infracao_comportamento_risco",
    "Retorno proibido": "infracao_comportamento_risco",
    "Participar de racha": "infracao_comportamento_risco",
    "Estacionar ou parar em local proibido": "infracao_comportamento_risco",
    "Transitar no acostamento": "infracao_comportamento_risco",
    "Transitar no Acostamento": "infracao_comportamento_risco",
    "Transitar na calçada": "infracao_comportamento_risco",
    "Modificação proibida": "infracao_comportamento_risco",
    "Deixar de acionar o farol da motocicleta (ou similar)": (
        "infracao_comportamento_risco"
    ),
    "Condutor desrespeitou a iluminação vermelha do semáforo": (
        "infracao_comportamento_risco"
    ),
    "Acesso irregular": "infracao_comportamento_risco",
    "Carga excessiva e/ou mal acondicionada": "infracao_comportamento_risco",
    "Demais falhas mecânicas ou elétricas": "falha_mecanica_veiculo",
    "Avarias e/ou desgaste excessivo no pneu": "falha_mecanica_veiculo",
    "Problema com o freio": "falha_mecanica_veiculo",
    "Problema na suspensão": "falha_mecanica_veiculo",
    "Faróis desregulados": "falha_mecanica_veiculo",
    "Ausência de sinalização": "infraestrutura_sinalizacao",
    "Sinalização mal posicionada": "infraestrutura_sinalizacao",
    "Sinalização encoberta": "infraestrutura_sinalizacao",
    "Deficiência do Sistema de Iluminação/Sinalização": ("infraestrutura_sinalizacao"),
    "Iluminação deficiente": "infraestrutura_sinalizacao",
    "Semáforo com defeito": "infraestrutura_sinalizacao",
    "Redutor de velocidade em desacordo": "infraestrutura_sinalizacao",
    "Pista esburacada": "infraestrutura_sinalizacao",
    "Pista em desnível": "infraestrutura_sinalizacao",
    "Afundamento ou ondulação no pavimento": "infraestrutura_sinalizacao",
    "Acostamento em desnível": "infraestrutura_sinalizacao",
    "Faixas de trânsito com largura insuficiente": "infraestrutura_sinalizacao",
    "Falta de acostamento": "infraestrutura_sinalizacao",
    "Falta de elemento de contenção que evite a saída do leito carroçável": (
        "infraestrutura_sinalizacao"
    ),
    "Obras na pista": "infraestrutura_sinalizacao",
    "Desvio temporário": "infraestrutura_sinalizacao",
    "Sistema de drenagem ineficiente": "infraestrutura_sinalizacao",
    "Demais falhas na via": "infraestrutura_sinalizacao",
    "Curva acentuada": "infraestrutura_sinalizacao",
    "Declive acentuado": "infraestrutura_sinalizacao",
    "Restrição de visibilidade em curvas horizontais": ("infraestrutura_sinalizacao"),
    "Restrição de visibilidade em curvas verticais": ("infraestrutura_sinalizacao"),
    "Chuva": "condicao_ambiental",
    "Neblina": "condicao_ambiental",
    "Fumaça": "condicao_ambiental",
    "Pista Escorregadia": "condicao_ambiental",
    "Acumulo de água sobre o pavimento": "condicao_ambiental",
    "Acumulo de óleo sobre o pavimento": "condicao_ambiental",
    "Acumulo de areia ou detritos sobre o pavimento": "condicao_ambiental",
    "Demais Fenômenos da natureza": "condicao_ambiental",
    "Pedestre cruzava a pista fora da faixa": "pedestre",
    "Pedestre andava na pista": "pedestre",
    "Entrada inopinada do pedestre": "pedestre",
    "Área urbana sem a presença de local apropriado para a travessia de "
    "pedestres": "pedestre",
    "Ingestão de álcool e/ou substâncias psicoativas pelo pedestre": "pedestre",
    "Ingestão de álcool ou de substâncias psicoativas pelo pedestre": "pedestre",
    "Pedestre - Ingestão de álcool/ substâncias psicoativas": "pedestre",
    "Mal súbito do condutor": "condicao_saude_condutor",
    "Transtornos Mentais (exceto suicidio)": "condicao_saude_condutor",
    "Suicídio (presumido)": "condicao_saude_condutor",
    "Obstrução Via tentativa Assalto": "obstrucao_via",
    "Animais na Pista": "obstrucao_via",
    "Objeto estático sobre o leito carroçável": "obstrucao_via",
    "Obstrução na via": "obstrucao_via",
}
